/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "singbox.go"

#include <stdlib.h>

// 日志回调声明与调用助手
typedef void (*LogCallback)(const char* msg);
static inline void callLog(LogCallback cb, const char* msg) {
	if (cb) { cb(msg); }
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// ProbeNodeDelay measures the server transport RTT without touching the running
// Box, its routes, or SOCKS inbounds. It is called on a Dart worker isolate.
//
extern __declspec(dllexport) int ProbeNodeDelay(char* requestJSON, int timeoutMs);
extern __declspec(dllexport) GoInt InitSingBox(void);
extern __declspec(dllexport) GoInt StartSingBox(char* configJSON);
extern __declspec(dllexport) char* SbDrainLogs(void);
extern __declspec(dllexport) GoInt StartSingBoxWithTunFd(char* configJSON, int fd);
extern __declspec(dllexport) GoInt StopSingBox(void);
extern __declspec(dllexport) GoInt IsRunning(void);
extern __declspec(dllexport) GoInt TestConfig(char* configJSON);
extern __declspec(dllexport) char* GetVersion(void);
extern __declspec(dllexport) void Cleanup(void);
extern __declspec(dllexport) char* SbGetLastError(void);
extern __declspec(dllexport) void FreeCString(char* p);
extern __declspec(dllexport) void RegisterLogCallback(LogCallback cb);
extern __declspec(dllexport) GoInt AddRouteRule(char* ruleJSON);
extern __declspec(dllexport) GoInt RemoveRouteRule(char* ruleJSON);
extern __declspec(dllexport) GoInt ReloadConfig(void);
extern __declspec(dllexport) GoInt ReplaceConfig(char* configJSON);
extern __declspec(dllexport) GoInt ClearRouteRules(void);
extern __declspec(dllexport) int ProbeTLS(char* host, int port, char* sni, int insecure, char* alpnCsv, int timeoutMs);
extern __declspec(dllexport) int ProbeQUIC(char* host, int port, char* sni, int insecure, char* alpnCsv, int timeoutMs);

#ifdef __cplusplus
}
#endif
